-- 用户表
CREATE TABLE `ET_USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '唯一主键',
  `USERNAME` varchar(32) NOT NULL COMMENT '用户名',
  `PASSWORD` varchar(32) NOT NULL COMMENT ' 用户密码',
  `GENDER` varchar(6) DEFAULT NULL COMMENT '性别',
  `PHONE` varchar(32) DEFAULT NULL COMMENT '电话',
  `ETOAKNO` varchar(32) NOT NULL COMMENT '易途学员编号',
  `AGE` int(4) DEFAULT NULL COMMENT '年龄',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;